### ISSUE TITLE
validation on scenario

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#415]
We should only hit this if the user is using a graphical **flow** frequency function - a rating is not required for stage freq
![image](https://user-images.githubusercontent.com/25163165/176042910-215768b5-61e7-4aa3-b317-e7df4dba836f.png)

**Comment by codymccoy** [comment]
This should be fixed now. I will test more when the graphical logic is submitted. 

The red asterisk should appear when a graphical is selected. It is currently not showing when an analytical freq is selected. You can save without an element in the combo being selected.

![image](https://user-images.githubusercontent.com/47757848/176045348-26b2e2d1-712f-4523-a1a5-61a2976d589f.png)

**Comment by rnugent3** [comment]
Could the message please be ".....when using a graphical _flow_ frequency function?

**Comment by rnugent3** [comment]
on what branch may I find this fix?

**Comment by codymccoy** [comment]
Updated the message:
![image](https://user-images.githubusercontent.com/47757848/176206108-9f7ef9eb-34a8-4151-8058-c8fd3ee78904.png)

**Comment by rnugent3** [comment]
The validation is still not quite right. See the two images below. I've selected a graphical _stage_-frequency function as the frequency relationship for this impact area scenario, so I don't need a stage-discharge function. I still hit the rating curve message. 

![image](https://user-images.githubusercontent.com/25163165/176206349-8fa02d87-38e2-42a8-bcc9-faded9c1bbdb.png)
![image](https://user-images.githubusercontent.com/25163165/176206368-ad687094-56a7-4922-bdd8-e3d36344e5c8.png)

There are three possibilities here:
1. We have an analytical flow-frequency function. We need a rating curve. 
2. We have a graphical flow-frequency function. We need a rating curve. 
3. We have a graphical stage-frequency function. No need for a rating curve.

**Comment by codymccoy** [comment]
Oh, ok, i was just checking if it was graphical or not, but i need to check if it is graphical and flow. I'm on it.

**Comment by codymccoy** [comment]
This is fixed on fda_results_testing branch. 

The message above is only when the user has selected a graphical flow frequency so I think we can leave it.

**Comment by codymccoy** [comment]
I am going too fast. This is not fixed yet. I didn't see that there are two cases. Maybe combining the message is the way to go.

**Comment by rnugent3** [comment]
Combined message sounds good to me, thanks.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/176214527-4693ece8-d5fe-46e3-88a5-4ab6d14d013c.png)

![image](https://user-images.githubusercontent.com/47757848/176214568-c3957a89-5e3f-461c-b2cb-e5ddb5cecdb7.png)

![image](https://user-images.githubusercontent.com/47757848/176214602-f51bc5fb-1304-45b0-868e-80b64841d3ac.png)

I believe this is now completed.

**Comment by rnugent3** [comment]
Perfect. Thank you!!
